Disply logs for failed Jobs.
socialwifi/kubepy pull request #32
Opened 2019-05-14 08:45 UTC by Behoston

2019-06-26 15:34 UTC, jgoclawski requested changes

2019-06-26 15:34 UTC, jgoclawski commented on kubepy/appliers.py
> +            for line in str(stdout).split('\\n'):
It's a bit overcomplicated to work on raw `bytes` type. 
You can go with:

```
  for line in stdout.decode().splitlines():
```

I'd also drop prefixing every line with stdout. kubectl logs mixes stdout and stderr anyway ([28167](https://github.com/kubernetes/kubernetes/issues/28167)), so what you call `stderr` here is not caontainer's `stderr` but `kubectl logs`'s `stderr` :)
That would leave us with a clean:
```
  print(stdout.decode())
```

2019-06-26 15:34 UTC, jgoclawski commented on kubepy/appliers.py
> +                return 'Init container failed!', init_container_status['state']['terminated']['message']
It's misleading to return an arbitrary string and pretend it came from stdout.
As mentioned above: maybe let's drop stdout/stderr distinction?

2019-06-27 12:47 UTC, pguz commented
Hi,

I have just made some tests using this pull and everything seems to work. I look forward to see these changes merged.

Have a nice day,
Paweł

2019-06-27 15:41 UTC, jgoclawski approved these changes
LGTM :+1:

2019-06-27 15:42 UTC, merged