Add support for ConfigMap
socialwifi/kubepy pull request #35
Opened 2019-08-30 16:16 UTC by glowka

Hey! 
I wanted to use `ConfigMap` instead of `Secret` for non-confidential data, but it turned out that kubepy currently does not support it, but it can be easilly added by extending `ResourceApplier.usable_with` with `ConfigMap`.

2019-10-18 16:15 UTC, glowka commented
Hey @jgoclawski  @Behoston could you take a look here?

2019-11-05 15:18 UTC, pguz requested changes
Looks good to me, but please make refactoring changes in the separate commit.

2019-11-06 17:54 UTC, glowka commented
> Looks good to me, but please make refactoring changes in the separate commit.

@pguz  Done

2019-11-07 08:57 UTC, pguz approved these changes

2019-11-07 08:59 UTC, merged